syntax = "proto3";

option csharp_namespace = "Catalog.API.Protos";

service CatalogService {
	rpc GetProduct (GetProductRequest) returns (ProductResponse);
	rpc GetProducts (GetProductsByIdsRequest) returns (GetProductsByIdsResponse);
}

message GetProductsByIdsRequest {
	repeated string productIds = 1;
}

message GetProductRequest {
	string productId = 1;
}

message ProductResponse {
	string productId = 1;
	string name = 2;
	string description = 3;
	string price = 4;
}

message GetProductsByIdsResponse {
	repeated CatalogProduct products = 1;
}

message CatalogProduct {
	string productId = 1;
	string name = 2;
	string description = 3;
	string price = 4;
}
